### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by franck-fourel** [thtliife/servicenow-sync#16]
[Enter steps to reproduce:]

1. Configure the file for ServiceNow sync
1. Setup proxy as described in doc.
2. Retrieve the file. Works fine. 
3. Make changes in the file
4. The first time I tried to sync the file to servicenow, I receieved the below error: 
```log
Uncaught TypeError: Cannot read property 'trim' of undefined
```

5. Then any attempt to get info from serviceNow for any file I get an other error: 

```log
An error occurred retrieving Test from https://instance.service-now.com
Error details: Error: write EPROTO 0:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:c:\users\electron\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:769: 
```

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [servicenow-sync](https://github.com/thtliife/servicenow-sync) package 0.2.17

### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At C:\Users\fournelf\.atom\packages\servicenow-sync\lib\modules\servicenow-sync-utils.coffee:387

TypeError: Cannot read property 'trim' of undefined
    at Object.checkSum (/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:387:53)
    at /packages/servicenow-sync/lib/servicenow-sync.coffee:99:44
    at Request._callback (/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:672:16)
    at self.callback (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:319:10)
    at onwrite (_stream_writable.js:337:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:463:13)
    at TLSSocket.Socket._destroy (net.js:504:3)
    at WriteWrap.afterWrite (net.js:797:10)
```

### Commands

```
     -8:10.7.0 window:toggle-dev-tools (div.package-detail.panels-item)
     -2:55.6.0 core:confirm (input.hidden-input)
  5x -2:54 core:backspace (input.hidden-input)
     -2:52.6.0 core:confirm (input.hidden-input)
     -2:12.9.0 tree-view:remove (div.tool-panel.tree-view)
     -1:52.5.0 servicenow-sync:sync (input.hidden-input)
     -1:35.9.0 core:paste (input.hidden-input)
     -1:28.1.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:51.9.0 editor:newline (input.hidden-input)
  2x -0:49 core:backspace (input.hidden-input)
     -0:44.2.0 core:move-right (input.hidden-input)
     -0:41.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
autocomplete-xml 0.9.4 
compare-files 0.8.0 
daylight-ui 0.2.2 
git-control 0.9.0 
git-plus 7.9.3 
github-atom-light-syntax 0.5.0 
language-batchfile 0.7.0 
language-powershell 4.0.0 
line-diff-details 1.8.0 
minimap 4.28.2 
minimap-git-diff 4.3.1 
minimap-split-diff 0.3.7 
monokai 0.22.0 
qolor 0.4.2 
servicenow-sync 0.2.17 
sort-lines 0.14.0 
split-diff 1.4.3 
tablr 1.8.3 
xml-tools 0.2.1 
```

**Comment by thtliife** [comment]
Hi @franck-fourel,
This is happening as servicenow-sync doesn’t appear to be handling the proxy correctly on first time configuration with the sync function. 
Does the error go away once atom is restarted?

**Comment by sadmicrowave** [comment]
Any updates? I'd like to use this solution for editing JS files.  Or know if there is another solution being used instead
