### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by prathviraj080** [thtliife/servicenow-sync#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.4
**Thrown From**: [servicenow-sync](https://github.com/thtliife/servicenow-sync) package 0.2.14

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Users/prathviraj.gavani/Downloads/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2Fprathviraj.gavani%2FServiceNow%20Codes%22%2C%22%2FUsers%2Fprathviraj.gavani%2FchromeExt%2FServiceNowSuperScripter%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fprathviraj.gavani%2FServiceNow%20Codes%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%2C%7B%22pathToOpen%22%3A%22%2FUsers%2Fprathviraj.gavani%2FchromeExt%2FServiceNowSuperScripter%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2FUsers%2Fprathviraj.gavani%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FUsers%2Fprathviraj.gavani%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F_p%2F0yn73qbx5hv2sbycj3hk5qhs_r3tmw%2FT%2F%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x5581EA9C%3A0x0%3A0x0%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22HOME%22%3A%22%2FUsers%2Fprathviraj.gavani%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.sbdhQceHlY%2FRender%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.rbLlcP5NRd%2FListeners%22%2C%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22LOGNAME%22%3A%22prathviraj.gavani%22%2C%22XPC_SERVICE_NAME%22%3A%22com.github.atom.191164%22%2C%22USER%22%3A%22prathviraj.gavani%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Fprathviraj.gavani%2F.atom%22%7D%2C%22appVersion%22%3A%221.14.4%22%2C%22atomHome%22%3A%22%2FUsers%2Fprathviraj.gavani%2F.atom%22%2C%22shellLoadTime%22%3A429%7D:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:674:31)
    at Request.self.callback (/packages/servicenow-sync/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/servicenow-sync/node_modules/request/request.js:1126:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/servicenow-sync/node_modules/request/request.js:1046:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:14.5.0 servicenow-sync:configure-file (input.hidden-input)
     -0:12.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-terminal 0.8.0 
minimap 4.25.7 
servicenow-sync 0.2.14 
```

**Comment by thtliife** [comment]
Hi @prathviraj080, 
Could you please add steps to reproduce the error?

**Comment by thtliife** [comment]
Note to self...
As far as I can tell, this issue may occur if either:
*  A user does not have access to the file being pushed
*  Atom is not able to communicate with service now for some reason (Usually a proxy)

_Really hard to diagnose without reproduction steps..._

**Comment by bloodess** [comment]
Hi ! Sorry for my late.

I just enter the url and the credentials on the setting plugin page.
Then I press the "get info" and this error is throw.

The credentials are good, but the ServiceNow instance is only "reachable" by a proxy.

Sorry for my bad english, if you want further information, don't hesitate.

**Comment by thtliife** [comment]
Is your proxy configured as per the PROXY section at the bottom of the [readme](https://github.com/thtliife/servicenow-sync#proxy-support)?

**Comment by azhornyak** [comment]
Here is my steps to reproduce: 
1. Install Atom 1.20.1
2. Install package servicenow-sync version 0.2.17
3. Open the Command Pallette, and type Servicenow Sync: Configure File in order to open file from ServiceNow (like in yourgif) 
4. Get message 'File not yet saved' 'In order to use Servicenow Sync, you must save this file. Would you like to save it now?'  (but there are no any files open)
5.  nothing happens for 3-5 times
6. Getting Error:

`TypeError: Cannot read property 'getPath' of undefined
at Object.syncFileExists (file:///C:/Users/username/.atom/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:380:28)
at Object.viewRemoteFile (file:///C:/Users/username/.atom/packages/servicenow-sync/lib/modules/servicenow-sync-utils.coffee:709:25)
at Object.viewRemote (file:///C:/Users/username/.atom/packages/servicenow-sync/lib/servicenow-sync.coffee:135:19)
at HTMLElement.subscriptions.add.atom.commands.add.servicenow-sync:view-remote (file:///C:/Users/username/.atom/packages/servicenow-sync/lib/servicenow-sync.coffee:67:95)
at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\username\AppData\Local\atom\app-1.20.1\resources\app\src\command-registry.js:265:35)
at C:\Users\username\AppData\Local\atom\app-1.20.1\resources\app\src\command-registry.js:3:65
at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\username\AppData\Local\atom\app-1.20.1\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:621:22)
at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\username\AppData\Local\atom\app-1.20.1\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:412:28)
at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\username\AppData\Local\atom\app-1.20.1\resources\app\src\window-event-handler.js:100:42)
at HTMLDocument.<anonymous> (C:\Users\username\AppData\Local\atom\app-1.20.1\resources\app\src\window-event-handler.js:3:65)
The error was thrown from the servicenow-sync package. This issue has already been reported.`

**Comment by thtliife** [comment]
@azhornyak You need to have a file open.
At the moment, you must have a file open in atom and saved to disk, in order for servicenow-sync to be able to save the file it pulls from ServiceNow.

In future builds, this will not be necessary, as i will not be relying on the local filename to store settings for the file.
